apiVersion: v1
kind: Service
metadata:
  name: nfs-exporter
  labels:
    k8s-app: nfs-exporter
    app: nfs-exporter
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "NFSExporter"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9689"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9689
    protocol: TCP
  selector:
    app: nfs-exporter
