apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nfs-exporter
  labels:
    k8s-app: nfs-exporter
  namespace: kube-system
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: nfs-exporter
  namespaceSelector:
    matchNames:
    - kube-system
  endpoints:
  - port: http-metrics
    interval: 30s